### ISSUE TITLE
Cant change default  timeSlot time 

### ISSUE THREAD

**Issue by ZainabMohd** [jacobsidford/react-timecalendar#10]
hi there, 

great work but somehow I cannot manage to change the default value of 30 for the timeSlot property. Any clue?

regards

**Comment by jacobsidford** [comment]
Hey Zainab, 
Sorry it seems I left a typo in from manual recently.

I have now fixed this for you in 2.0.1.

Let me know if there's anything else you'd like to see implemented soon.

**Comment by ZainabMohd** [comment]
thanks much appreciated. It would be nice to have more control over timings. like for instance opportunity to have breaks.
